'''title'''
__title__ = 'pyimagedl'
'''description'''
__description__ = 'Imagedl: Search and download images from specific websites'
'''url'''
__url__ = 'https://github.com/CharlesPikachu/imagedl'
'''version'''
__version__ = '0.1.2'
'''author'''
__author__ = 'Charles'
'''email'''
__email__ = 'charlesblwx@gmail.com'
'''license'''
__license__ = 'Apache License 2.0'
'''copyright'''
__copyright__ = 'Copyright 2022 Charles'